insert into public.permissions (key, module_key, action, description)
values
  ('manage_all', 'core', 'all', 'Acceso total'),
  ('view_reports', 'reports', 'read', 'Ver reportes'),
  ('manage_branding', 'branding', 'manage', 'Administrar branding'),
  ('manage_settings', 'settings', 'manage', 'Administrar configuracion'),
  ('manage_users', 'users', 'manage', 'Administrar usuarios'),
  ('manage_roles', 'roles', 'manage', 'Administrar roles'),
  ('dashboard.read', 'dashboard', 'read', 'Ver dashboard'),
  ('customers.read', 'customers', 'read', 'Ver clientes'),
  ('customers.create', 'customers', 'create', 'Crear clientes'),
  ('customers.update', 'customers', 'update', 'Editar clientes'),
  ('customers.delete', 'customers', 'delete', 'Eliminar clientes'),
  ('services.read', 'services', 'read', 'Ver servicios'),
  ('services.create', 'services', 'create', 'Crear servicios'),
  ('services.update', 'services', 'update', 'Editar servicios'),
  ('services.delete', 'services', 'delete', 'Eliminar servicios'),
  ('products.read', 'products', 'read', 'Ver productos'),
  ('products.create', 'products', 'create', 'Crear productos'),
  ('products.update', 'products', 'update', 'Editar productos'),
  ('products.delete', 'products', 'delete', 'Eliminar productos'),
  ('appointments.read', 'appointments', 'read', 'Ver citas y reservas'),
  ('appointments.create', 'appointments', 'create', 'Crear citas y reservas'),
  ('appointments.update', 'appointments', 'update', 'Editar citas y reservas'),
  ('appointments.delete', 'appointments', 'delete', 'Eliminar citas y reservas'),
  ('sales.read', 'sales', 'read', 'Ver ventas'),
  ('sales.create', 'sales', 'create', 'Registrar ventas'),
  ('sales.update', 'sales', 'update', 'Editar ventas'),
  ('sales.delete', 'sales', 'delete', 'Eliminar ventas'),
  ('users.read', 'users', 'read', 'Ver usuarios y empleados'),
  ('users.manage', 'users', 'manage', 'Administrar usuarios, membresias e invitaciones'),
  ('roles.read', 'roles', 'read', 'Ver roles y permisos'),
  ('roles.manage', 'roles', 'manage', 'Administrar roles y permisos'),
  ('settings.read', 'settings', 'read', 'Ver configuracion del negocio'),
  ('settings.update', 'settings', 'update', 'Editar configuracion del negocio'),
  ('branding.read', 'branding', 'read', 'Ver branding y tema'),
  ('branding.update', 'branding', 'update', 'Editar branding y assets'),
  ('reports.read', 'reports', 'read', 'Ver reportes')
on conflict (key) do nothing;
